Use R CMD check instead of devtools::check().

diff --git a/travis-tests b/travis-tests
--- a/travis-tests
+++ b/travis-tests
@@ -185,7 +185,13 @@ read_args "$@"
 # Check
 if [[ $CHECK == yes ]] ; then
 	echo "Checking package..."
-	make check || exit 1
+	make r.check || exit 1
+	# Use `R CMD check` instead of `devtools::test()` because the later failed once Travis-CI:
+	#   Warning in config_val_to_logical(check_incoming) :
+	#     cannot coerce ‘FALSE false’ to logical
+	#   Error in if (check_incoming) check_CRAN_incoming(!check_incoming_remote) : 
+	#     missing value where TRUE/FALSE needed
+	#   Execution halted
 fi
 
 # Test
