List status of all databases.

diff --git a/travis-tests b/travis-tests
--- a/travis-tests
+++ b/travis-tests
@@ -1,6 +1,94 @@
 #!/bin/bash
 # vi: fdm=marker
 
+# Constants {{{1
+################################################################
+
+YES=yes
+
+# Global variables {{{1
+################################################################
+
+DEBUG=0
+DRY_RUN=
+
+# Print help {{{1
+################################################################
+
+function print_help {
+	echo "Usage: travis-tests [options]"
+	echo
+	echo "This script is used to run tests on Travis-CI.org."
+	echo "The following environment variables are used:"
+	echo "  CHECK: If set yo \"yes\", then a check of the package will be run using \"devtools::check()\"."
+	echo "  MODE: The mode in which to test the database connectors. Either \"online\" or \"offline\"."
+	echo "  DBS: A comma separated list of databases to test. By default all database connectors are tested."
+	echo "  EXCLUDE_DBS: A comma separated list of database connectors to exclude from testing."
+	echo "See file \".travis.yml\"."
+	echo
+	echo "Options:"
+	echo "   -g, --debug          Debug mode."
+	echo "   -h, --help           Print this help message."
+	echo "   -n, --dry-run        Do not run anything."
+}
+
+# Error {{{1
+################################################################
+
+error() {
+
+	local msg="$1"
+
+	echo "ERROR: $msg" >&2
+
+	exit 1
+}
+
+# Print debug msg {{{1
+################################################################
+
+function print_debug_msg {
+
+	local dbglvl=$1
+	local dbgmsg=$2
+
+	[[ $DEBUG -ge $dbglvl ]] && echo "[DEBUG] $dbgmsg" >&2
+}
+
+# Read args {{{1
+################################################################
+
+function read_args {
+
+	local args="$*" # save arguments for debugging purpose
+	
+	# Read options
+	while true ; do
+		case $1 in
+			-n|--dry-run)       DRY_RUN=$YES ;;
+			-g|--debug)         DEBUG=$((DEBUG + 1)) ;;
+			-h|--help)          print_help ; exit 0 ;;
+			-) error "Illegal option $1." ;;
+			--) error "Illegal option $1." ;;
+			--*) error "Illegal option $1." ;;
+			-?) error "Unknown option $1." ;;
+			-[^-]*) split_opt=$(echo $1 | sed 's/^-//' | sed 's/\([a-zA-Z]\)/ -\1/g') ; set -- $1$split_opt "${@:2}" ;;
+			*) break
+		esac
+		shift
+	done
+	shift $((OPTIND - 1))
+
+	# Remaining arguments?
+	[[ -z "$*" ]] || error "Remaining arguments (\"$*\") are not allowed."
+
+	# Debug
+	print_debug_msg 1 "Arguments are : $args"
+	print_debug_msg 1 "Env var CHECK : $CHECK"
+	print_debug_msg 1 "Env var MODE : $MODE"
+	print_debug_msg 1 "Env var DBS : $DBS"
+	print_debug_msg 1 "Env var EXCLUDE_DBS : $EXCLUDE_DBS"
+}
 # Get out of order databases {{{1
 ################################################################
 
@@ -11,35 +99,39 @@ get_ooo_dbs() {
 	echo $dbs
 }
 
-# Update databases to process {{{1
+# Exclude out of order databases {{{1
 ################################################################
 
-update_dbs_to_process() {
-	local ooo_dbs=$1
+exclude_ooo_dbs() {
+
+	# Get out of order databases
+	local ooo_dbs=$(get_ooo_dbs | tr ' ' ',')
+
+	# Change separator
 	local IFS=,
 
 	# Update databases to test
-	if [[ -n $DATABASES ]] ; then
+	if [[ -n $DBS ]] ; then
 		new_db_list=()
-		for db in $DATABASES ; do
+		for db in $DBS ; do
 			if [[ $ooo_dbs =~ (^|,)$db($|,) ]] ; then
 				echo "***** Database \"$db\" is out of order, and will not be tested."
 			else
 				new_db_list+=($db)
 			fi
 			if [[ ${#new_db_list[@]} == 0 ]] ; then
-				export DATABASES=
+				DBS=none
 			else
-				export DATABASES="${new_db_list[@]}"
+				DBS="${new_db_list[@]}"
 			fi
 		done
 
 	# Update databases to exclude
-	elif [[ -n $DONT_TEST_DBS ]] ; then
+	elif [[ -n $EXCLUDE_DBS ]] ; then
 		for db in $ooo_dbs ; do
-			if [[ ! $DONT_TEST_DBS =~ (^|,)$db($|,) ]] ; then
+			if [[ ! $EXCLUDE_DBS =~ (^|,)$db($|,) ]] ; then
 				echo "***** Database \"$db\" is out of order, and will not be tested."
-				export DONT_TEST_DBS=$DONT_TEST_DBS,$db
+				EXCLUDE_DBS=$EXCLUDE_DBS,$db
 			fi
 		done
 
@@ -49,7 +141,7 @@ update_dbs_to_process() {
 		for db in $ooo_dbs ; do
 			echo "***** Database \"$db\" is out of order, and will not be tested."
 		done
-		export DONT_TEST_DBS=$ooo_dbs
+		EXCLUDE_DBS=$ooo_dbs
 	fi
 }
 
@@ -58,32 +150,37 @@ update_dbs_to_process() {
 
 run_tests() {
 
-	if [[ -z $DATABASES && -z $DONT_TEST_DBS ]] ; then
+	if [[ $DBS == none ]] ; then
 		echo "Nothing to test. Exiting."
 	else
 	 	echo -n "Testing package"
 
 		# Databases to test
-		if [[ -n $DATABASES ]] ; then
-			echo -n " on database(s) $DATABASES"
+		if [[ -n $DBS ]] ; then
+			echo -n " on database(s) $DBS"
+			export DATABASES=$DBS
 		else
 			echo -n " on all databases"
 		fi
 
 		# Exclude databases
-		if [[ -n $DONT_TEST_DBS ]] ; then
-			echo -n " except on database(s) $DONT_TEST_DBS"
+		if [[ -n $EXCLUDE_DBS ]] ; then
+			echo -n " except on database(s) $EXCLUDE_DBS"
+			export DONT_TEST_DBS=$EXCLUDE_DBS
 		fi
 
 		# Mode
-		echo " in mode $MODES."
+		echo " in mode $MODE."
+		export MODES=$MODE
 
-		make test
+		[[ $DRY_RUN == $YES ]] || make test
 	fi
 }
 
 # Main {{{1
 ################################################################
+
+read_args "$@"
 
 # Check
 if [[ $CHECK == yes ]] ; then
@@ -92,19 +189,14 @@ if [[ $CHECK == yes ]] ; then
 fi
 
 # Test
-if [[ -n $MODES ]] ; then
+if [[ -n $MODE ]] ; then
 
-	if [[ -n $DATABASES && -n $DONT_TEST_DBS ]] ; then
-		echo "Error, both DATABASES and DONT_TEST_DBS env vars are defined." >&2
-		exit 1
-	fi
+	[[ $MODE == online || $MODE == offline ]] || error "MODE env var must be set either to online or offline."
 
-	# Get out of order databases
-	ooo_dbs=$(get_ooo_dbs | tr ' ' ',')
-	echo ooo_dbs=$ooo_dbs
+	[[ -n $DBS && -n $EXCLUDE_DBS ]] && error "Error, both DBS ($DBS) and EXCLUDE_DBS ($EXCLUDE_DBS) env vars are defined."
 
-	# Update list of databases to process
-	update_dbs_to_process $ooo_dbs
+	# Exclude out of order databases
+	[[ $MODE == offline ]] || exclude_ooo_dbs
 
 	# Run tests
 	run_tests
