Improve error messages on R version issue.

diff --git a/inst/templates/R_front b/inst/templates/R_front
--- a/inst/templates/R_front
+++ b/inst/templates/R_front
@@ -57,7 +57,7 @@ END_HELP_MSG
 ################################################################
 
 error() {
-	local msg="$1"
+	local msg="$*"
 
 	echo "[ERROR] $msg at ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" >&2
 	quit 1
@@ -67,9 +67,10 @@ error() {
 ################################################################
 
 warning() {
-	local msg="$1"
+	local msg="$*"
 
-	[[ -n $QUIET ]] || echo "[WARNING] $msg at ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" >&2
+	[[ -n $QUIET ]] || echo "[WARNING] $msg at"\
+		"${BASH_SOURCE[1]}:${BASH_LINENO[0]}" >&2
 }
 
 # Debug {{{1
@@ -77,7 +78,7 @@ warning() {
 
 debug() {
 	local lvl=$1
-	local msg="$2"
+	local msg="$*"
 
 	[[ $DEBUG -ge $lvl ]] && echo "[DEBUG] $msg" >&2
 }
@@ -86,7 +87,7 @@ debug() {
 ################################################################
 
 info() {
-	local msg="$1"
+	local msg="$*"
 
 	[[ -n $QUIET ]] || echo "[INFO] $msg" >&2
 }
@@ -185,6 +186,8 @@ function select_version {
 			if [[ -z $version_name ]] ; then
 				[[ -f $VERSIONS_FILE ]] || download_versions_file
 				version_name=$(grep ": $R_VERSION" "$VERSIONS_FILE" | sed 's/^\(.*\):.*$/\1/')
+				[[ -n $version_name ]] || error "Cannot find any version name"\
+					"in \"$VERSIONS_FILE\" for version \"$R_VERSION\"."
 			fi
 
 			# Set selected version
@@ -193,6 +196,7 @@ function select_version {
 				Devel)        SELECTED_VERSION=devel ;;
 				Release)      SELECTED_VERSION=release ;;
 				current)      SELECTED_VERSION=current ;;
+				*)            error "Unknown version name \"$version_name\"." ;;
 			esac
 
 		# Unknown version
